name: devops-learnings ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  markdown-ci:
    defaults:
      run:
        shell: bash

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23
      name: markdown-lint - Certifications
      with:
        config: .markdownlint.json
        globs: 'docs/certifications/*.md'

    - uses: DavidAnson/markdownlint-cli2-action@ded1f9488f68a970bc66ea5619e13e9b52e601cd # v23
      name: markdown-lint - Tooling
      with:
        config: .markdownlint.json
        globs: 'docs/tooling/*.md'

  deploy-zensical:
    defaults:
      run:
        shell: bash
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: markdown-ci
    runs-on: ubuntu-latest
    

    steps:

    - name: Configure Github Pages
      uses: actions/configure-pages@v6

    - name: Checkout the Repo
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

    - name: Install the latest version of uv and set the python version to 3.14
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        python-version: 3.14

    - name: Install Dependencies with uv
      run: uv sync

    - name: Build Site
      run: uv run zensical build --clean

    - name: Upload artifact for deployment
      uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b # v4
      with:
        path: site

    - name: Deploy Pages
      uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5
      id: deployment
